# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generated_widget.ui',
# licensing of 'generated_widget.ui' applies.
#
# Created: Wed Aug 12 18:45:11 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(501, 481)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mainVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.mainHorizontalLayout = QtWidgets.QHBoxLayout()
        self.mainHorizontalLayout.setSpacing(0)
        self.mainHorizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.mainHorizontalLayout.setObjectName("mainHorizontalLayout")
        self.diskParamFormWidget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.diskParamFormWidget.setObjectName("diskParamFormWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.diskParamFormWidget)
        self.formLayout_2.setContentsMargins(4, 4, 4, 4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lengthLabel = QtWidgets.QLabel(self.diskParamFormWidget)
        self.lengthLabel.setObjectName("lengthLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lengthLabel)
        self.lengthLineEdit = QtWidgets.QLineEdit(self.diskParamFormWidget)
        self.lengthLineEdit.setObjectName("lengthLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lengthLineEdit)
        self.outerDiameterLabel = QtWidgets.QLabel(self.diskParamFormWidget)
        self.outerDiameterLabel.setObjectName("outerDiameterLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.outerDiameterLabel)
        self.outerDiameterLineEdit = QtWidgets.QLineEdit(self.diskParamFormWidget)
        self.outerDiameterLineEdit.setObjectName("outerDiameterLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.outerDiameterLineEdit)
        self.bottomCurvatureRadiusLabel = QtWidgets.QLabel(self.diskParamFormWidget)
        self.bottomCurvatureRadiusLabel.setTextFormat(QtCore.Qt.RichText)
        self.bottomCurvatureRadiusLabel.setWordWrap(False)
        self.bottomCurvatureRadiusLabel.setObjectName("bottomCurvatureRadiusLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bottomCurvatureRadiusLabel)
        self.bottomCurvatureRadiusLineEdit = QtWidgets.QLineEdit(self.diskParamFormWidget)
        self.bottomCurvatureRadiusLineEdit.setPlaceholderText("")
        self.bottomCurvatureRadiusLineEdit.setObjectName("bottomCurvatureRadiusLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bottomCurvatureRadiusLineEdit)
        self.topCurvatureRadiusLabel = QtWidgets.QLabel(self.diskParamFormWidget)
        self.topCurvatureRadiusLabel.setObjectName("topCurvatureRadiusLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.topCurvatureRadiusLabel)
        self.topCurvatureRadiusLineEdit = QtWidgets.QLineEdit(self.diskParamFormWidget)
        self.topCurvatureRadiusLineEdit.setPlaceholderText("")
        self.topCurvatureRadiusLineEdit.setObjectName("topCurvatureRadiusLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.topCurvatureRadiusLineEdit)
        self.topCurvatureRelativeOrientationLabel = QtWidgets.QLabel(self.diskParamFormWidget)
        self.topCurvatureRelativeOrientationLabel.setObjectName("topCurvatureRelativeOrientationLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.topCurvatureRelativeOrientationLabel)
        self.topCurvatureRelativeOrientationLineEdit = QtWidgets.QLineEdit(self.diskParamFormWidget)
        self.topCurvatureRelativeOrientationLineEdit.setObjectName("topCurvatureRelativeOrientationLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.topCurvatureRelativeOrientationLineEdit)
        self.centreHoleDiameterLabel = QtWidgets.QLabel(self.diskParamFormWidget)
        self.centreHoleDiameterLabel.setObjectName("centreHoleDiameterLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.centreHoleDiameterLabel)
        self.centreHoleDiameterLineEdit = QtWidgets.QLineEdit(self.diskParamFormWidget)
        self.centreHoleDiameterLineEdit.setObjectName("centreHoleDiameterLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.centreHoleDiameterLineEdit)
        self.tendonDistanceFromAxisLabel = QtWidgets.QLabel(self.diskParamFormWidget)
        self.tendonDistanceFromAxisLabel.setObjectName("tendonDistanceFromAxisLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.tendonDistanceFromAxisLabel)
        self.tendonDistanceFromAxisLineEdit = QtWidgets.QLineEdit(self.diskParamFormWidget)
        self.tendonDistanceFromAxisLineEdit.setObjectName("tendonDistanceFromAxisLineEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.tendonDistanceFromAxisLineEdit)
        self.tendonGuideDiameterLabel = QtWidgets.QLabel(self.diskParamFormWidget)
        self.tendonGuideDiameterLabel.setObjectName("tendonGuideDiameterLabel")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.tendonGuideDiameterLabel)
        self.tendonGuideDiameterLineEdit = QtWidgets.QLineEdit(self.diskParamFormWidget)
        self.tendonGuideDiameterLineEdit.setObjectName("tendonGuideDiameterLineEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.tendonGuideDiameterLineEdit)
        self.numberOfTendonGuidesLabel = QtWidgets.QLabel(self.diskParamFormWidget)
        self.numberOfTendonGuidesLabel.setObjectName("numberOfTendonGuidesLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.numberOfTendonGuidesLabel)
        self.numberOfTendonGuidesLineEdit = QtWidgets.QLineEdit(self.diskParamFormWidget)
        self.numberOfTendonGuidesLineEdit.setObjectName("numberOfTendonGuidesLineEdit")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.numberOfTendonGuidesLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.exportPathLabel = QtWidgets.QLabel(self.diskParamFormWidget)
        self.exportPathLabel.setObjectName("exportPathLabel")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.exportPathLabel)
        self.exportPathLineEdit = QtWidgets.QLineEdit(self.diskParamFormWidget)
        self.exportPathLineEdit.setObjectName("exportPathLineEdit")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.exportPathLineEdit)
        self.mainHorizontalLayout.addWidget(self.diskParamFormWidget)
        self.controlVerticalLayout = QtWidgets.QVBoxLayout()
        self.controlVerticalLayout.setSpacing(1)
        self.controlVerticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.controlVerticalLayout.setContentsMargins(-1, 0, 0, -1)
        self.controlVerticalLayout.setObjectName("controlVerticalLayout")
        self.generateButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.generateButton.setFlat(False)
        self.generateButton.setObjectName("generateButton")
        self.controlVerticalLayout.addWidget(self.generateButton)
        self.resetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.resetButton.setObjectName("resetButton")
        self.controlVerticalLayout.addWidget(self.resetButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.controlVerticalLayout.addItem(spacerItem1)
        self.mainHorizontalLayout.addLayout(self.controlVerticalLayout)
        self.mainVerticalLayout.addLayout(self.mainHorizontalLayout)
        self.errorTextbox = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.errorTextbox.setReadOnly(True)
        self.errorTextbox.setOverwriteMode(True)
        self.errorTextbox.setObjectName("errorTextbox")
        self.mainVerticalLayout.addWidget(self.errorTextbox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.lengthLineEdit.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.outerDiameterLineEdit.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.bottomCurvatureRadiusLineEdit.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.topCurvatureRadiusLineEdit.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.topCurvatureRelativeOrientationLineEdit.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.centreHoleDiameterLineEdit.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.tendonDistanceFromAxisLineEdit.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.tendonGuideDiameterLineEdit.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.numberOfTendonGuidesLineEdit.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.exportPathLineEdit.clear)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL("clicked()"), self.errorTextbox.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Disk Generator", None, -1))
        self.lengthLabel.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Length (mm)*</span></p></body></html>", None, -1))
        self.lengthLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Required", None, -1))
        self.outerDiameterLabel.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Outer diameter (mm)*</span></p></body></html>", None, -1))
        self.outerDiameterLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Required", None, -1))
        self.bottomCurvatureRadiusLabel.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Bottom curvature radius (mm)</span><span style=\" font-size:10pt;\"><br/>(Empty: no bottom curvature)</span></p></body></html>", None, -1))
        self.topCurvatureRadiusLabel.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Top curvature radius (mm)</span><span style=\" font-size:10pt;\"><br/>(Empty: no top curvature)</span></p></body></html>", None, -1))
        self.topCurvatureRelativeOrientationLabel.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Top curvature orientation (deg)</span><span style=\" font-size:10pt;\"><br/>(Empty: Default to 0)</span></p></body></html>", None, -1))
        self.centreHoleDiameterLabel.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Centre hole diameter (mm)</span><span style=\" font-size:10pt;\"><br/>(Empty: no centre hole)</span></p></body></html>", None, -1))
        self.tendonDistanceFromAxisLabel.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tendon guide distance from axis</span><span style=\" font-size:10pt;\"><br/>(Empty: no tendon guide)</span></p></body></html>", None, -1))
        self.tendonGuideDiameterLabel.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tendon guide diameter (mm)</span><span style=\" font-size:10pt;\"><br/>(Empty: no tendon guide)</span></p></body></html>", None, -1))
        self.numberOfTendonGuidesLabel.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tendon guide number</span><span style=\" font-size:10pt;\"><br/>(Empty: no tendon guide)</span></p></body></html>", None, -1))
        self.exportPathLabel.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Export path</span><span style=\" font-size:10pt;\"><br/>(Empty: &quot;./DATE_TIME.step&quot;)</span></p></body></html>", None, -1))
        self.generateButton.setText(QtWidgets.QApplication.translate("Dialog", "Generate", None, -1))
        self.resetButton.setText(QtWidgets.QApplication.translate("Dialog", "Reset", None, -1))

